name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build problem.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: problem.tex
          working_directory: problem
          latexmk_use_xelatex: true
          extra_system_packages: |
            fonts-noto-cjk
            fonts-arphic-gkai00mp

      - name: Build solution.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: solution.tex
          working_directory: solution
          latexmk_use_xelatex: true
          extra_system_packages: |
            fonts-noto-cjk
            fonts-arphic-gkai00mp

      - name: Release Package
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            problem/problem.pdf
            solution/solution.pdf
